name: "Deploy"
on:
  push:
    branches: "master"
  pull_request:
    branches: "master"
  workflow_dispatch:

jobs:
  Deploy:
    runs-on: "ubuntu-latest"

    permissions:
      id-token: write
      contents: read

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"

      - name: "Install Deno"
        uses: "denoland/setup-deno@v1"
        with:
          deno-version: vx.x.x

      - name: "Build"
        run: "deno task build"

      - name: "Deno Deploy"
        uses: "denoland/deployctl@v1"
        with:
          project: "ysun"
          entrypoint: "main.ts"
          root: "."
